services:
  - type: web
    name: marketplace
    runtime: node
    plan: free
    buildCommand: npm install && npm --prefix client install --include=dev && npm run client:build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_COOKIE_EXPIRES_IN
        value: "7"
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
